backend/controllers/TextsController.php
<?php

class TextsController extends Controller
{

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
        return array(
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('delete', 'index', 'view', 'create', 'update', 'remove', 'edit','filter'),
                'users' => array('root'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
	}


	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Sourcemessage;
        $translates=new Message();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Sourcemessage']) AND isset($_POST['Message']))
		{
            $transaction=Yii::app()->db->beginTransaction();

			$tmp=$_POST['Sourcemessage'];
            $tmp['category']=(!empty($tmp['category_new']))?$tmp['category_new']:$tmp['category'];
            $model->attributes=$tmp;
			if(!$model->validate() OR !$model->save()){
                $transaction->rollback();
                $this->throwError($model->errors);
            }

            $translates->attributesM = $_POST['Message'];

            if(!$translates->multiSave($model->id,'id')){
                $transaction->rollBack();
                $this->throwError($translates->errors);
            }

            $transaction->commit();
            $this->ajaxThrowContent();
		}
        $translateCategories=TextsAdmin::factory()->getTextsCategories();

		$render=$this->renderPartial('create',array(
			'model'=>$model,
			'translateCategories'=>$translateCategories,
			'translates'=>$translates,
		),true);
        $this->throwSuccess(array('content' => $render),'modal_form');
	}

    /**
     *filter for texts
     */
    public function actionFilter(){
        $this->ajaxThrowContent();
    }

    private function ajaxThrowContent()
    {
        $TextsAdmin=new TextsAdmin;
        $dataProvider=$TextsAdmin->getTextsByPages();
        $translateCategories=$TextsAdmin->getTextsCategories();
        $getQuery=MYCHtml::makeGetQuery(array('filter_category','filter_text','filter_translate'));
        $render=$this->renderPartial('index',array(
            'dataProvider'=>$dataProvider,
            'getQuery'=>$getQuery,
            'translateCategories'=>$translateCategories,
        ),true);
        $this->throwSuccess(array('content' => $render, 'div' => 'mainContentID'));
    }

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionEdit($id)
	{
		$model=$this->loadModel($id);
        $messageModel=Message::model();
        $translates=$messageModel->getDataForEdit($id,'id');
        if(isset($_POST['Sourcemessage']) AND isset($_POST['Message']))
        {
            $transaction=Yii::app()->db->beginTransaction();

            $tmp=$_POST['Sourcemessage'];
            $tmp['category']=(!empty($tmp['category_new']))?$tmp['category_new']:$tmp['category'];
            $model->attributes=$tmp;
            if(!$model->validate() OR !$model->save()){
                $transaction->rollback();
                $this->throwError($model->errors);
            }

            $messageModel->attributesM = $_POST['Message'];

            if(!$messageModel->multiSave($model->id,'id')){
                $transaction->rollBack();
                $this->throwError($messageModel->errors);
            }

            $transaction->commit();
            $this->ajaxThrowContent();
        }
        $translateCategories=TextsAdmin::factory()->getTextsCategories();

        $render=$this->renderPartial('edit',array(
            'model'=>$model,
            'translateCategories'=>$translateCategories,
            'translates'=>$translates,
        ),true);
        $this->throwSuccess(array('content' => $render),'modal_form');
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();
		$this->ajaxThrowContent();
	}

    public function actionRemove(){
        $textsToDelete=Yii::app()->request->getParam('check',array());
        $strId=implode(',', $textsToDelete);
        $model=new Sourcemessage();
        $model->deleteAll('id IN (' . $strId . ')');
        $this->ajaxThrowContent();
    }

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $TextsAdmin=new TextsAdmin;
		$dataProvider=$TextsAdmin->getTextsByPages();
        $translateCategories=$TextsAdmin->getTextsCategories();
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/cms/modules/show.js',CClientScript::POS_END);
        $getQuery=MYCHtml::makeGetQuery(array('filter_category','filter_text','filter_translate'));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'getQuery'=>$getQuery,
			'translateCategories'=>$translateCategories,
		));
	}



	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Sourcemessage::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

}

backend/views/texts/_form.php
<?php
/* @var $this TextsController */
/* @var $model Sourcemessage */
/* @var $form CActiveForm */
?>

<div class="modal-body">

    <?php echo CHtml::form('#', "POST",
    array('class' => 'form-horizontal', 'id' => 'modalEditFormId', 'enctype' => 'multipart/form-data'));
    echo CHtml::hiddenField('submit', '1');
    ?>
    <div class="control-group" >
        <label class="control-label" for="textsMessageId"><?php echo Yii::t('texts', 'Category');?></label>

        <div class="controls" id="textsCategoryTabs">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#textsCategory"> <?php echo Yii::t('texts', 'Choose') ?></a></li>
                <li><a href="#textsNewCategory"> <?php echo Yii::t('texts', 'New category') ?></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="textsCategory">
                    <?php
                    echo  CHtml::dropDownList('Sourcemessage[category]', $model->category, CHtml::listData($translateCategories, 'category', 'category'), array('id' => 'categoryList'));
                    ?>
                </div>
                <div class="tab-pane" id="textsNewCategory">
                    <?php
                    echo CHtml::textField('Sourcemessage[category_new]', '', array('id' => 'categoryNew'));
                    ?>
                </div>
            </div>
        </div>

    </div>
    <div class="control-group">
        <label class="control-label" for="textsMessageId"><?php echo Yii::t('texts', 'Source text');?></label>

        <div class="controls">
            <?php
            echo CHtml::textField('Sourcemessage[message]', $model->message, array('textsMessageId'))
            ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for=""><?php echo Yii::t('texts', 'Translates');?></label>

        <div class="controls">
            <?php
            $this->widget('multiLangsTabs',array(
                'modelTexts'=>$translates,
                'view'=>'application.views.texts.langs._translates'));
            ?>
        </div>
    </div>

    <script>
        $(function () {
            $('#textsCategoryTabs a').click(function (e) {
                e.preventDefault();
                $(this).tab('show');
            })
        })
    </script>
    <?php echo CHtml::endForm(); ?>

</div><!-- form -->

backend/views/texts/create.php
<?php
/* @var $this TextsController */
/* @var $model Sourcemessage */

?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><?php echo Yii::t("texts","Create new multilanguage text translate") ?></h3>

</div>

<?php $this->renderPartial('_form', array('model'=>$model,'translateCategories'=>$translateCategories,'translates'=>$translates)); ?>

<div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal"><i class="icon-remove "></i> <?php echo  Yii::t("main",'Close')?></a>
    <a href="<?php echo Yii::app()->createUrl('texts/create')?>" id='modalSubmitBtnId' class="btn btn-success"
       title="<?php echo Yii::t("main",'Save')?>"><i class=" icon-ok icon-white"></i> <?php echo Yii::t("main",'Save');?></a>
</div>

<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/cms/modules/editmodal.js"></script>

backend/views/texts/edit.php
<?php
/* @var $this TextsController */
/* @var $model Sourcemessage */
?>
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">×</button>
<h3><?php echo Yii::t("texts","Edit multilanguage text translate") ?></h3>

</div>

<?php $this->renderPartial('_form', array('model'=>$model,'translateCategories'=>$translateCategories,'translates'=>$translates)); ?>

<div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal"><i class="icon-remove "></i> <?php echo  Yii::t("main",'Close')?></a>
    <a href="<?php echo Yii::app()->createUrl('texts/edit/'.$model->id)?>" id='modalSubmitBtnId' class="btn btn-success"
       title="<?php echo Yii::t("main",'Save')?>"><i class=" icon-ok icon-white"></i> <?php echo Yii::t("main",'Save');?></a>
</div>

<script type="text/javascript" src="<?php echo Yii::app()->baseUrl ?>/js/cms/modules/editmodal.js"></script>

backend/views/texts/index.php
<?php
/* @var $this TextsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs = array(
    'Multi language texts and translates',
);

$this->box_title = Yii::t('admin', 'Multi language texts and translates');
$this->leftMenu = $this->renderPartial('/texts/menu/left', array(), true);
?>
<?php
echo CHtml::form(Yii::app()->createUrl('texts'), 'get');
?>
<?php
echo CHtml::endForm();
?>
<?php
$this->widget('addRemoveBtns',
    array(
        'addUrl' => Yii::app()->createUrl(lang_url . 'texts/create/'),
        'removeUrl' => Yii::app()->createUrl(lang_url . 'texts/remove/'),
        'msgRemove' => Yii::t("texts", "Do you really want to delete the selected texts"),
        'modal' => true,
    ));
?>

<table class="table table-striped table-condensed">
    <thead>
    <th class="text-center table-check-column"><?php echo CHtml::checkBox('selectAll', false, array('onclick' => "$('input[name*=\'check\']').attr('checked', this.checked);")) ?></th>
    <th class="span4"><?php echo Yii::t('texts', 'Original text')?></th>
    <th class="span3"><?php echo Yii::t('texts', 'Dictionary')?></th>
    <th class="span4"><?php echo Yii::t('texts', 'Translate to current language')?></th>
    <th class="table-action-column"><?php echo Yii::t("main", 'Action'); ?></th>
    </thead>
    <tbody>
    <tr>
        <td></td>
        <td>
            <div class="filter-container ">
                <?php
                    echo CHtml::hiddenField('filterUrl',Yii::app()->createUrl('texts/filter'),array('id'=>'filterUrlId'));
                    echo CHtml::textField('filter_text',Yii::app()->request->getParam('filter_text'),array('class'=>'filter'))
                ?>
            </div>
        </td>
        <td>
            <div class="filter-container ">
                <?php
                $arrSearch=CHtml::listData($translateCategories, 'category', 'category');
                $static=array('0'=>Yii::t('texts','Select dictionary'));
                echo  CHtml::dropDownList('filter_category', Yii::app()->request->getParam('filter_category'),$static+ $arrSearch, array('class'=>'filter-select filter'));
                ?>
            </div>
        </td>
        <td>
            <div class="filter-container ">
                <?php
                echo CHtml::textField('filter_translate',Yii::app()->request->getParam('filter_translate'),array('class'=>'filter'))
                ?>
            </div>
        </td>
        <td></td>
    </tr>
    <?php
    $data = $dataProvider->getData();
    foreach ($data as $key => $text):
        ?>
    <tr>
        <td class="text-center">
            <?php
            echo Chtml::checkBox('check[]', false, array('value' => $text->id));
            ?>
        </td>
        <td><?php echo $text->message?></td>
        <td><?php echo $text->category?></td>
        <td>
            <?php
            foreach ($text->messages as $translate) {
                echo $translate->language . ': ' . $translate->translation . "<br>";
            }
            ?>
        </td>
        <td class="table-action-column">
            <?php
            $this->widget('editRemoveBtnGroup', array(
                'editUrl' => Yii::app()->createUrl('texts/edit/' . $text->id . $getQuery),
                'delUrl' => Yii::app()->createUrl('texts/delete/' . $text->id . $getQuery),
                'delQuestion' => Yii::t("texts", "Do you really want to delete the selected text"),
                'modal' => true,
            ));
            ?>
        </td>
    </tr>
        <?php endforeach; ?>

    </tbody>
</table>
<?php
$this->widget('pagination', array('count' => $dataProvider->getTotalItemCount(), 'perPage' => 15, 'url' => Yii::app()->createUrl(lang_url . 'texts' . $getQuery)));
?>